### ISSUE TITLE
PR先は一意にprototypeにすべきですか？

### ISSUE THREAD

**Issue by yameholo** [YoshiRi/JPandENbst#13]
#6 を皮切りにPR先がmasterからprototypeにように見られますが、新規機能追加に関係のないもの（誤字脱字・タイポの修正など）であってもprototypeをPR先にすべきでしょうか？

**Comment by YoshiRi** [comment]
私自身最新の仕事は追えてないのですが、共同編集者さんと話して頃合いを見てprototypeをmasterにマージするつもりではおります。出来るならprototypeを確認して頂いてPR貰えたほうが後にpickするよりも楽で助かります。

**Comment by yameholo** [comment]
masterはオーナー（及び共同編集者）がprototypeをマージするのみで、基本的にPR先はprototypeが望ましい。という認識で大丈夫でしょうか？

**Comment by YoshiRi** [comment]
基本的にはprototypeで開発を進める方針なので出来ればそうして頂けると助かります。あまりこの手の開発に慣れていないのですがこれは一般的ではありませんか？

**Comment by yameholo** [comment]
prototypeについて確認しました。
自分もあまり詳しくないので一般的かわかりません。すみません。

**Comment by ehki** [comment]
gitの一般的とされる運用ルールよくわからないですよね。
一人くらい運用慣れしている人がいると良いのですが…。
ここは(まだ)失敗しても被害者が少ないレポジトリなのでいろいろ試していただけると嬉しいです。
みんなで勉強していきましょう。

**Comment by ehki** [comment]
GItの運用方針については
[GithubでのWeb上からのマージの仕方3種とその使いどころ](https://qiita.com/ko-he-8/items/94e872f2154829c868df)
の、「[結局どうしたいか](https://qiita.com/ko-he-8/items/94e872f2154829c868df#%E7%B5%90%E5%B1%80%E3%81%A9%E3%81%86%E3%81%97%E3%81%9F%E3%81%84%E3%81%8B)」が参考になると思います。

> - master
> -- 常にきれいなcommit logで一本道にしたい
> -- 基本的にdevelopブランチ以外をマージしない
> -- developのどこまでがマージされたかわかるようにしたい
> -- マージするたびにバージョンが上がる(ex. 1.0.12→1.0.13)
> - develop
> -- topic_branchや外部からのpull_requestはここに受ける
> -- ここもきれいなcommit logを保ちたい
> - topic_branch
> -- developに取り込んだのち削除
> -- 開発速度優先で細かくcommitしコミットメッセージもある程度適当

のようです。私も`prototype`から`topic_branch`を生やしてはプルリクエストしてmergeしては消し、とやってみています。

**Comment by ehki** [comment]
という私が上述の基本ルールを学ぶ前は大変汚い運用をやらかしていたというのはログを見れば明らかなのですが…。
