### ISSUE TITLE
エントリのfileのパスで日本語とみなされる

### ISSUE THREAD

**Issue by ehki** [YoshiRi/JPandENbst#2]
日本人向けツールであるため日本語で書きます。
addJPflag.py
において、各エントリの全stringをis_japaneseで判別しているため、例えばfileキーに日本語が含まれていると日本語エントリとみなされます。
gitを使い慣れていないのですが修正済ファイルがあるのでプルリクエストをすぐ送ります。

**Comment by YoshiRi** [comment]
ehkiさん。ありがとうございます。有用そうですが，必要パッケージが少ない方がいいと思ったので別名かブランチを切って対応しようか考えています。

確かに日本語のpathがあり得ることは失念していました。逆に他のところには紛れそうにないと思ったのでpathの部分を無視するために単語毎に区切った後，`\`や`/`で処理をエスケープする仕組みを導入してみました。

もし良ければテストしていただけませんか？

**Comment by ehki** [comment]
ありがとうございます。各tokenのチェックで、`/`や`\`を使いエスケープもいいと思います。ただ、文献タイトルに`/`を使う著者もたまにいますので、キーを指定して検索をかけたほうが確実そうです。

正規表現でキー指定の検索バージョンを書いてみましたので、PRを更新しました。
`bibtexparser`は使用していません。
コミットが連なってしまいましたが、一つに纏めたほうがよいのですかね…？
