### ISSUE TITLE
IEEJ.bstの名前間文字

### ISSUE THREAD

**Issue by nakashin303** [YoshiRi/JPandENbst#24]
IEEJ.bstの名前間文字
現在全角カンマ「，」で仕切られていますが、
電気学会論文誌への投稿手引詳細
https://www.iee.jp/pub/contribution_guide/detail/#2-5-5
によると、中点「・」のほうが良さそうです。
オプションで変えられると良いと思います。

**Comment by ehki** [comment]
ありがとうございます、修正しました。

```
% 日本語文献において、著者間の仕切り文字の設定
% default: {bbl.ieej.jp.author.sep} { "・" }
%          {bbl.ieej.en.author.sep} { ", " }
FUNCTION {bbl.ieej.jp.author.sep} { "・" }
FUNCTION {bbl.ieej.en.author.sep} { ", " }
```
このオプションで変更できるようにしました。
