### ISSUE TITLE
英語の参考文献において，著者が2名のときにA and Bと表示させたい

### ISSUE THREAD

**Issue by opuyoshi** [YoshiRi/JPandENbst#72]
jIEEEtran.bstにおいて，著者が2人の場合，現状では
` J. Sato, and S. Hayashi, “Part of jpbook2,” in Jpbook2, 2nd ed. Tokyo, Japan: JP Press, 2012, pp. 100–200.`
というように，著者名がA, and Bと表示されると思います．
これを，
`J. Sato and S. Hayashi, “Part of jpbook2,” in Jpbook2, 2nd ed. Tokyo, Japan: JP Press, 2012, pp. 100–200.`
のように，著者名をA and Bと表示させるためにはどのような設定を行えばよいでしょうか．

ご確認よろしくお願いいたします．

**Comment by ehki** [comment]
こんにちは、Issueありがとうございます。
ご指摘のカンマは本来存在すべきではないですね。
たとえば本家IEEEtranのドキュメントpdf
http://mirrors.ctan.org/macros/latex/contrib/IEEEtran/IEEEtran_HOWTO.pdf
の文献[4]は
```
[4] H. Kopka and P. W. Daly, Guide to LATEX, 4th ed. Harlow, England: Addison-Wesley, 2003.
```
です。設定では切り替えられず、 `format.names` 関数をいじる必要がありますので、少々お待ちください。

具体的には、本家の `format.names` 関数内のコードブロック
```
              t "others" =
                { " " * bbl.etal emphasize * }
                { numnames #2 >
                    { "," * }
                    { skip$ }
                  if$
                  bbl.and
                  space.word * t do.name.latex.cmd *
                }
              if$
```
を
```
              t "others" =
                { japanese.flag #1 =
                    { "・" * bbl.etal }
                    { " " * bbl.etal emphasize }
                  if$ *
                }
                { author.sep.last * t do.name.latex.cmd * }
              if$
```
と改変していますが、このあたりを変える必要がありそうです。

**Comment by opuyoshi** [comment]
確かに本家では著者数が２人のときで場合分けしてそうですね．
お忙しいところ大変申し訳ありませんが，修正のほどよろしくお願いいたします．

**Comment by ehki** [comment]
ブランチ [bugfix/improper_comma_in_numnames_is_two](https://github.com/ehki/jIEEEtran/tree/bugfix/improper_comma_in_numnames_is_two) に修正ファイルをアップしました。お試しいただけますか？
こちらのファイルですね。
https://github.com/ehki/jIEEEtran/blob/bugfix/improper_comma_in_numnames_is_two/jieeetran/jIEEEtran.bst
